### ISSUE TITLE
Could not resolve com.regula.documentreader.fullrfid:core:+

### ISSUE THREAD

**Issue by armandolujafresh** [regulaforensics/DocumentReader-Android#17] opened 2020-04-14 00:53 UTC
Hi, it appears that the repository hosting Regula dependencies is unaccessible or has changed.

These error messages are being logged by the build server:

`Could not GET 'https://raw.githubusercontent.com/iProov/android/master/maven/com/regula/documentreader/fullrfid/core/'. Received status code 400 from server: Bad Request`

`Could not resolve com.regula.documentreader:api:+`

`Could not get resource 'https://raw.githubusercontent.com/iProov/android/master/maven/com/regula/documentreader/api/'.`

`Could not GET 'https://raw.githubusercontent.com/iProov/android/master/maven/com/regula/documentreader/api/'. Received status code 400 from server: Bad Request`

We have not changed our implementation, it matches the sample app & the tutorial:

build.gradle (project)
```
implementation 'com.regula.documentreader.fullrfid:core:+@aar'
implementation('com.regula.documentreader:api:+@aar') {
        transitive = true
    }
```
build.gradle (app)
```
allprojects {
    repositories {
        google()
        jcenter()
        maven { url 'https://oss.jfrog.org/libs-snapshot/' }
        maven { url 'https://raw.githubusercontent.com/iProov/android/master/maven/' }
        maven { url 'http://maven.regulaforensics.com/RegulaDocumentReader' }
    }
}
```

I would really appreciate if you could take a look at this issue.

**Comment by vyakimchik** [comment] 2020-04-14 07:45
Hi. It seems that the issue doesn't relate to our maven repository according to the provided error. Is it possible somehow to reproduce the issue in our demo project?

**Comment by armandolujafresh** [comment] 2020-04-14 16:25
Yes, you must try building on a new computer, or clear your gradle cache
Reproduction steps:
1. clear your gradle cache
2. download demo project
3. build

**Comment by vyakimchik** [comment] 2020-04-15 06:50
It works. No issues are found. What does this repo contain: `https://raw.githubusercontent.com/iProov/android/master/maven/`? It can't be accessed via the browser, the error which you described is returned. Maybe it's the source of the issue.

**Comment by vyakimchik** [comment] 2020-04-21 20:21
I'll close the issue for now because there hasn't been any activity. Feel free to reopen it if you are still experiencing this problem.

**Closed by vyakimchik** 2020-04-21 20:21 UTC
